adding workflows
aruba-uxi/celery-sqlalchemy-scheduler pull request #2
Opened 2022-02-11 08:48 UTC by jengelhard

2022-02-11 09:14 UTC, NJABULO-NDLOVU commented on dev-requirements.in
>  black
`black <= 18`

2022-02-11 09:14 UTC, NJABULO-NDLOVU commented on Justfile
> -	@just requirements
keep this line

2022-02-11 10:45 UTC, NJABULO-NDLOVU commented on .github/workflows/package.yml
> +        python-version: 3.8
3.10

2022-02-11 10:47 UTC, NJABULO-NDLOVU commented on Justfile
> -	pip-compile
`pip install pipenv ` before running pipenv lock

2022-02-11 10:48 UTC, NJABULO-NDLOVU commented on Justfile
> -	pip-compile
then comment that it's only there temporarily

2022-02-11 12:05 UTC, evanstjabadi requested changes

2022-02-11 12:05 UTC, evanstjabadi commented on README.md
> +[![Python Version](https://img.shields.io/badge/python-3.10-blue?logo=Python&logoColor=yellow)](https://docs.python.org/3.10/)
Put 3.8 to correspond with the version

2022-02-14 08:34 UTC, evanstjabadi approved these changes
LGMT

2022-02-14 08:40 UTC, merged